
import { db } from "./firebase";
import { 
  collection, 
  addDoc, 
  getDocs, 
  query, 
  orderBy, 
  doc, 
  updateDoc, 
  deleteDoc,
  serverTimestamp,
  where
} from "firebase/firestore";
import { Transaction, ImportedRevenue } from './types';

// Omit 'id' as it will be generated by Firestore
type TransactionData = Omit<Transaction, 'id'>;
type ImportedRevenueData = Omit<ImportedRevenue, 'id'>;

// Salvar transação
export function saveTransaction(data: TransactionData, userId: string) {
  const transactionsCol = collection(db, "transacoes");
  return addDoc(transactionsCol, {
    ...data,
    tipoInterno: 'transacao',
    criadoPor: userId,
    criadoEm: serverTimestamp()
  });
}

// Ler todas as transações (sem filtro de usuário)
export function getTransactions() {
  const transactionsCol = collection(db, "transacoes");
  const q = query(
    transactionsCol,
    orderBy("date", "desc")
  );
  return getDocs(q);
}

// Atualizar transação
export function updateTransaction(id: string, data: Partial<TransactionData>) {
    const transactionDoc = doc(db, "transacoes", id);
    return updateDoc(transactionDoc, data);
}

// Deletar transação
export function deleteTransaction(id: string) {
    const transactionDoc = doc(db, "transacoes", id);
    return deleteDoc(transactionDoc);
}

// --- RECEITAS IMPORTADAS ---

export function saveImportedRevenue(data: ImportedRevenueData, userId: string) {
    const col = collection(db, "transacoes");
    return addDoc(col, {
        ...data,
        tipoInterno: "receita_importada",
        criadoPor: userId,
        criadoEm: serverTimestamp()
    });
}

export function getImportedRevenues() {
    const col = collection(db, "transacoes");
    const q = query(col, where("tipoInterno", "==", "receita_importada"), orderBy("date", "desc"));
    return getDocs(q);
}

export function getRevenuesByPeriod(startDate: string, endDate: string) {
    const col = collection(db, "transacoes");
    const q = query(
        col, 
        where("tipoInterno", "==", "receita_importada"),
        where("data", ">=", startDate),
        where("data", "<=", endDate)
    );
    return getDocs(q);
}

export function deleteImportedRevenue(id: string) {
    const docRef = doc(db, "transacoes", id);
    return deleteDoc(docRef);
}
