

import { db } from "./firebase";
import { 
  collection, 
  addDoc, 
  getDocs, 
  query, 
  where, 
  orderBy, 
  doc, 
  updateDoc, 
  deleteDoc,
  serverTimestamp
} from "firebase/firestore";
import { Transaction } from './types';

// Omit 'id' as it will be generated by Firestore
type TransactionData = Omit<Transaction, 'id'>;

// Salvar transação
export function saveTransaction(data: TransactionData, userId: string) {
  const transactionsCol = collection(db, "transacoes");
  return addDoc(transactionsCol, {
    ...data,
    criadoPor: userId,
    criadoEm: serverTimestamp()
  });
}

// Ler transações para um usuário específico
export function getTransactions(userId: string) {
  const transactionsCol = collection(db, "transacoes");
  const q = query(
    transactionsCol,
    where("criadoPor", "==", userId),
    orderBy("date", "desc")
  );
  return getDocs(q);
}

// Atualizar transação
export function updateTransaction(id: string, data: Partial<TransactionData>) {
    const transactionDoc = doc(db, "transacoes", id);
    return updateDoc(transactionDoc, data);
}

// Deletar transação
export function deleteTransaction(id: string) {
    const transactionDoc = doc(db, "transacoes", id);
    return deleteDoc(transactionDoc);
}